import { notFound, redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { getEmployeeSession } from "@/lib/session";
import { PrintButton } from "./PrintButton";

type QuotePageProps = {
  params: Promise<{
    id: string;
  }>;
};

function money(value: { toString(): string } | number) {
  return Number(value.toString()).toFixed(2);
}

function vehicleLabel(vehicle: {
  year: string;
  make: string;
  model: string;
  color: string | null;
  licensePlate: string | null;
  vin: string | null;
}) {
  return [
    vehicle.color,
    vehicle.year,
    vehicle.make,
    vehicle.model,
    vehicle.licensePlate ? `Plate ${vehicle.licensePlate}` : null,
    vehicle.vin ? `VIN ${vehicle.vin}` : null,
  ]
    .filter(Boolean)
    .join(" ");
}

export default async function QuotePage({ params }: QuotePageProps) {
  const employee = await getEmployeeSession();

  if (!employee) {
    redirect("/");
  }

  const { id } = await params;
  const orderId = Number(id);

  if (!Number.isInteger(orderId)) {
    notFound();
  }

  const order = await prisma.order.findUnique({
    where: {
      id: orderId,
    },
    include: {
      customer: true,
      vehicle: true,
      quotedByEmployee: true,
      lineItems: {
        orderBy: {
          createdAt: "asc",
        },
      },
    },
  });

  if (!order) {
    notFound();
  }

  if (!order.quotedByEmployee) {
    redirect(`/orders/${order.id}?error=quotedByRequired`);
  }

  const subtotal = order.lineItems.reduce(
    (total, item) => total + Number(item.lineTotal.toString()),
    0,
  );
  const generatedAt = new Intl.DateTimeFormat("en-US", {
    dateStyle: "long",
    timeStyle: "short",
  }).format(new Date());

  return (
    <main className="quote-print-shell">
      <div className="quote-screen-actions">
        <PrintButton />
      </div>

      <section className="quote-document">
        <header className="quote-header">
          <div>
            <p className="eyebrow">Healdton Service Center</p>
            <h1>Quote</h1>
            <p>Order {order.orderNumber}</p>
          </div>
          <div className="quote-meta">
            <span>Generated</span>
            <strong>{generatedAt}</strong>
            <span>Generated By</span>
            <strong>{order.quotedByEmployee.name}</strong>
            {order.isCompanyCar && order.companyNameSnapshot ? (
              <>
                <span>Company</span>
                <strong>{order.companyNameSnapshot}</strong>
              </>
            ) : null}
          </div>
        </header>

        <div className="quote-info-grid">
          <section>
            <h2>Customer</h2>
            <p>
              <strong>
                {order.customer.firstName} {order.customer.lastName}
              </strong>
            </p>
            <p>{order.customer.phone}</p>
            {order.customer.email ? <p>{order.customer.email}</p> : null}
          </section>

          <section>
            <h2>Vehicle</h2>
            {order.vehicle ? (
              <p>{vehicleLabel(order.vehicle)}</p>
            ) : (
              <p>No vehicle attached.</p>
            )}
          </section>
        </div>

        <table className="quote-table">
          <thead>
            <tr>
              <th>Item</th>
              <th>Qty</th>
              <th>Unit</th>
              <th>Adjustment</th>
              <th>Total</th>
            </tr>
          </thead>
          <tbody>
            {order.lineItems.map((item) => (
              <tr key={item.id}>
                <td>
                  <strong>{item.description}</strong>
                  {item.notes ? <span>{item.notes}</span> : null}
                </td>
                <td>{money(item.quantity)}</td>
                <td>${money(item.unitPrice)}</td>
                <td>
                  {item.complementary
                    ? "Complementary"
                    : Number(item.discountPercent.toString()) > 0
                      ? `${money(item.discountPercent)}% off`
                      : "-"}
                </td>
                <td>${money(item.lineTotal)}</td>
              </tr>
            ))}
          </tbody>
        </table>

        <div className="quote-total">
          <span>Subtotal</span>
          <strong>${money(subtotal)}</strong>
        </div>

        <footer className="quote-footer">
          <p>
            This quote is an estimate based on the listed services and parts.
            Final invoice may change if approved work changes.
          </p>
        </footer>
      </section>
    </main>
  );
}
